### PR TITLE
Create hello world application

### LINKED ISSUE #1: Create hello world application

### PR DESCRIPTION
**Pull request by divayprakash**
Closes #1

### CODE REVIEW

**Comment by divayprakash** [comment]
@shakeelmohamed Sorry about the mess of commits, I forgot to use the `AppCompatActivity` for backwards compatibility in dcab36c so had to revert that in fb60976 and finally fix it in 1e7dbd5. I'd suggest a squash and merge here.

**Comment by shakeelmohamed** [comment]
You'll need to add `.idea` to the `.gitignore` file and make sure that whole directory isn't checked into git before I can review this 😄

**Comment by divayprakash** [comment]
@shakeelmohamed On it!

**Comment by shakeelmohamed** [comment]
@divayprakash I think you'll need to run `git rm .idea` as well

**Comment by divayprakash** [comment]
@shakeelmohamed I've added `.idea/` to the `.gitignore` file in 1c8e3d1. For removing the files from the git index, I ran the command `git rm --cached `git ls-files -i --exclude-from=.gitignore`` in 55dfe01.

**Comment by shakeelmohamed** [comment]
LGTM, thanks @divayprakash. Let's get this ball rolling!

**Pull request merged**
